app:
    key:
        size: 64
        validation_duration: 24h
    database:
        username: backend_user
        password: backend_password
        hostnames: localhost:27017,localhost:27018,localhost:27019
        replicaset: rs0
        db: shoppinglist
        lists_collection: lists
        users_collection: users
    server:
        hostname: 0.0.0.0
        port: 8080

dbctl:
    database:
        hostnames: localhost:27017,localhost:27018,localhost:27019
        replicaset: rs0
        db: admin
        username: root
        password: password
    migrations:
        db: shoppinglist
        collection: migrations
