app:
    key:
        size: 64
        validation_duration: 24h
    database:
        username: backend_user
        password: backend_password
        hostname: localhost
        port: 27017
        db: shoplist
        lists_collection: lists
        users_collection: users
    server:
        hostname: 0.0.0.0
        port: 8080
        crt: ./server.crt
        key: ./server.key

dbctl:
    database:
        hostname: localhost
        port: 27017
        db: admin
        username: root
        password: password
    migrations:
        db: shoplist
        collection: migrations
