version: "3.8"
services:
  
  mongo-replica-setup:
    container_name: mongo-setup
    image: mongo
    restart: on-failure
    volumes:
      - ./mongodb/scripts/mongosetup.sh:/scripts/mongosetup.sh
    entrypoint: ["bash", "/scripts/mongosetup.sh" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    container_name: mongo1
    hostname: mongo1
    image: mongo
    restart: on-failure
    command: ["-f", "/etc/mongod.conf", "--keyFile", "/auth/file.key", "--replSet", "rs0", "--bind_ip_all"]
    ports: 
      - 27017:27017
    volumes:
      - ./services_data/dataMongo1:/data/db
      - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/file.key:/auth/file.key
    healthcheck:
      test: test $$(echo "rs.status().ok" | mongo -u root -p password --quiet) -eq 1
      interval: 30s
      start_period: 60s
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin

  mongo2:
    container_name: mongo2
    hostname: mongo2
    image: mongo
    command: ["-f", "/etc/mongod.conf", "--keyFile", "/auth/file.key", "--replSet", "rs0", "--bind_ip_all"]
    restart: on-failure
    ports:
      - 27018:27018
    volumes:
      - ./services_data/dataMongo2:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/file.key:/auth/file.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    depends_on: 
        - mongo1

  mongo3:
    container_name: mongo3
    hostname: mongo3
    image: mongo
    command: ["-f", "/etc/mongod.conf", "--keyFile", "/auth/file.key", "--replSet", "rs0", "--bind_ip_all"]
    restart: on-failure
    ports: 
      - 27019:27019 
    volumes:
      - ./services_data/dataMongo3:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/file.key:/auth/file.key
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: admin
    depends_on: 
        - mongo1

  adminui:
    image: mongo-express
    container_name: adminui
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo1, mongo2, mongo3
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password